# Generated by Django 4.2.3 on 2023-07-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
