# Generated by Django 4.2.3 on 2023-07-25 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_action_about_en_action_about_ru_action_about_uz_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.place'),
        ),
    ]
