# Generated by Django 4.2.3 on 2023-07-25 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_contact_place'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='comment',
        ),
    ]
